[package]
name = "imgpack"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.45", features = ["derive"] }
clap_derive = "4.5.45"
color_quant = "1.1.0"
image = "0.25.6"
oxipng = "9.1.5"
