# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  pkg:
    dir: ./adapter/cloudfunction
    cmds:
      - zip -r ../../tmp/app-$(date +%Y%m%d%H%M%S).zip *

  dev:
    desc: start dev server
    cmds:
      - go run -tags dev . --serve
