# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  package:
    cmds:
      - zip -r tmp/app.zip * -x "web/*" -x "tmp/*" -x "*.md"
      - mv tmp/app.zip tmp/app-$(date +%Y%m%d%H%M%S).zip
