# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  dev:
    desc: start dev server
    cmds:
      - go run -tags dev . --serve

  dockerbuild:
    desc: build docker image
    cmds:
      - cd findui && pnpm install && pnpm build
      - docker build --platform linux/amd64 --tag imgpack .
