name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
          - os: macos-15
            target: x86_64-apple-darwin
          - os: macos-15
            target: aarch64-apple-darwin
    env:
      ARCHIVE_NAME: imgpack-${{ github.ref_name }}-${{ matrix.platform.target }}
    steps:
      - uses: actions/checkout@v4
      - if: matrix.platform.os == 'ubuntu-24.04'
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - run: cargo install --path . --root dist --locked --target ${{ matrix.platform.target }}
      - run: tar -czf ${{ env.ARCHIVE_NAME }}.tar.gz -C dist/bin imgpack

      - uses: actions/upload-artifact@v4
        with:
          name: release-${{ env.ARCHIVE_NAME }}
          path: ${{ env.ARCHIVE_NAME }}.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: release-*
          path: dist

      - run: shasum -a 256 *.tar.gz > checksums.txt
        working-directory: dist

      - run: |
          cat <<'EOF' | envsubst > release.md
          # imgpack ${{ github.ref_name }}
          ## Installation
          ```bash
          cargo install --git https://github.com/enuesaa/imgpack --tag ${{ github.ref_name }}
          ```
          EOF

      - uses: softprops/action-gh-release@v2
        with:
          body_path: release.md
          files: dist/*
